In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_parquet('cleaned_dataset.parquet')

In [3]:
df.head()

                                            Features Category
0  hr administratormarketing associate hr adminis...       Hr
1  hr specialist u hr operation summary versatile...       Hr
2  hr director summary year experience recruiting...       Hr
3  hr specialist summary dedicated driven dynamic...       Hr
4  hr manager skill highlight hr skill hr departm...       Hr

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Features  2484 non-null   object
 1   Category  2484 non-null   object
dtypes: object(2)
memory usage: 38.9+ KB

In [5]:
# category is the target label 
# encoding category using labelencoder

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [7]:
le.fit(df['Category'])
df['Category']=le.transform(df['Category'])

In [8]:
df.head()

                                            Features  Category
0  hr administratormarketing associate hr adminis...        19
1  hr specialist u hr operation summary versatile...        19
2  hr director summary year experience recruiting...        19
3  hr specialist summary dedicated driven dynamic...        19
4  hr manager skill highlight hr skill hr departm...        19

In [9]:
df['Category'].unique()

array([19, 13, 20, 23,  1,  9, 18, 17,  2,  8, 22, 12, 14,  5, 10, 16,  3,
       15,  0, 11, 21,  7,  4,  6])

In [10]:
#train-test split

In [11]:
from sklearn.model_selection import train_test_split

x=df['Features']
y=df['Category']

x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2,random_state=42)

In [13]:
#TF-IDF

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
tfidf=TfidfVectorizer()
x_train_tfid=tfidf.fit_transform(x_train)
x_test_tfid=tfidf.transform(x_test)

In [16]:
x_train_tfid

<1987x38503 sparse matrix of type '<class 'numpy.float64'>'
	with 598756 stored elements in Compressed Sparse Row format>

In [17]:
x_train_tfid.shape

(1987, 38503)